version: '3'

services:

  user-api:
    image: mscblog/user-api:latest
    ports:
      - 3000:3000
    networks:
      main:
        aliases:
          - mscblog-user-api
    command: >
      /bin/bash -c "sleep 5; node ."

  article-api:
    image: mscblog/article-api:latest
    ports:
      - 3001:3000
    networks:
      main:
        aliases:
          - mscblog-article-api
    command: >
      /bin/bash -c "sleep 5; node ."

  graphql:
      image: mscblog/graphql:latest
      ports:
        - 3002:3030
      environment:
        USER_API: mscblog-user-api
        ARTICLE_API: mscblog-article-api
      networks:
        main:
          aliases:
            - mscblog
      command: >
        /bin/bash -c "sleep 5; node ."

networks:
  main:

volumes:
  yarn:
