http:
  port: 8080
admin:
  port: 9876
  hostname: localhost
apiEndpoints:
  user:
    host: '*'
    paths:
      - /api/me
      - /api/users/login
      - /api/users/logout
  article:
    host: '*'
    paths:
      - /api/articles
serviceEndpoints:
  user:
    url: ${USER_API}
  article:
    url: ${ARTICLE_API}
policies:
  - user-exists
  - proxy
pipelines:
  - user-api:
    apiEndpoints:
      - user
    policies:
      - proxy:
        - action:
            serviceEndpoint: user
            changeOrigin: true
  - article-api:
    apiEndpoints:
      - article
    policies:
      - user-exists:
      - proxy:
        - action:
            serviceEndpoint: article
            changeOrigin: true