http:
  port: 8080
admin:
  port: 9876
  hostname: localhost
apiEndpoints:
  user:
    host: '*'
    paths:
      - /api/me
      - /api/users/login
      - /api/users/logout
  graphql:
    host: '*'
    paths:
      - /graphql
      - /graphiql
serviceEndpoints:
  user:
    url: ${USER_API}
  graphql:
    url: ${GRAPHQL}
policies:
  - user-exists
  - proxy
pipelines:
  - user-api:
    apiEndpoints:
      - user
    policies:
      - proxy:
        - action:
            serviceEndpoint: user
            changeOrigin: true
  - article-api:
    apiEndpoints:
      - graphql
    policies:
      - user-exists:
      - proxy:
        - action:
            serviceEndpoint: graphql
            changeOrigin: true