http:
  port: 8080
admin:
  port: 9876
  hostname: localhost
apiEndpoints:
  users:
    host: '*'
    paths:
      - /api/me
      - /api/users/login
      - /api/users/logout
serviceEndpoints:
  users:
      url: ${USER_API}
policies:
  - user-exists
  - proxy
pipelines:
  my-api:
    apiEndpoints:
      - users
    policies:
      - proxy:
        - action:
            serviceEndpoint: users
            changeOrigin: true